casoDeEstudio/applications/home/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'home_app'

urlpatterns = [
path('', views.HomePageView.as_view(), name='inicio'),
]

casoDeEstudio/applications/libro/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'libros_app'

urlpatterns = [
    path('libros/', views.ListLibros.as_view(), name='libros'),
    path('librosCategoria/<categoria>/', views.ListLibrosCategoria.as_view(), name='libros-categoria'),
    path('libroDetalle/<pk>/', views.LibroDetailView.as_view(), name='libro-detalle'),
    path('categorias/', views.CategoriaListView.as_view(), name='categorias'),
]

casoDeEstudio/applications/usuario/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'users_app'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name = 'user-register'),
    path('login/', views.UserLoginView.as_view(), name = 'user-login'),
    path('logout/', views.UserLogoutView.as_view(), name = 'user-logout'),
    path('user-verification/<pk>/', views.CodeVerificationView.as_view(), name = 'user-verification'),
    path('compra/<pk>/', views.OrdenView.as_view(), name = 'user-compra'),
    path('lista-ordenes/', views.OrdenesView.as_view(), name = 'user-ordenes'),
]

casoDeEstudio/casoDeEstudio/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.libro.urls')),
    re_path('', include('applications.usuario.urls')),
    re_path('', include('applications.home.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

casoDeEstudio/templates/includes/header.html
<!--<div class="container-fluid">-->
<!--<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home_app:inicio' %}">Mexizon</a>
        <ul class="navbar-nav ml-auto" data-dropdown-menu>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'libros_app:libros' %}">Ver todos los libros</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'libros_app:categorias' %}">Ver generos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users_app:user-register' %}">Registrarte</a>
            </li>
                    {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="#">Ver mis pedidos</a>
            </li>
            <li class="nav-item">
                <p class="saludo-usuario">Hola {{user.nombre}}</p>
            </li>
                    {% else %}
              <li><a class="nav-link" href="{% url 'users_app:user-login' %}">Inicio de sesión</a></li>
                    {% endif %}
            <li class="nav-item">
              <a type="button" class="btn btn-primary" href="{% url 'users_app:user-logout' %}">Cerrar sesión</a>
            </li>
        </ul>
    </div>
</nav>-->
<!--
</div>-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-custom">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home_app:inicio' %}">Mexizon</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
              <a class="nav-link" href="{% url 'libros_app:libros' %}">Ver todos los libros</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'libros_app:categorias' %}">Ver generos</a>
          </li>
      </ul>
        <div class="navbar-derecha">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                    {% if user.is_authenticated %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'users_app:user-ordenes' %}">Ver mis pedidos</a>
          </li>
          <li class="nav-item">
              <p class="saludo-usuario">Hola {{user.nombre}}</p>
          </li>
          <li class="nav-item cerrar-sesion">
              <a type="button" class="btn btn-primary cerrar-sesion" href="{% url 'users_app:user-logout' %}">Cerrar sesión</a>
          </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'users_app:user-register' %}">Registrarte</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'users_app:user-login' %}">Inicio de sesión</a>
          </li>
          {% endif %}
      </ul>
        </div>
    </div>
  </div>
</nav>

casoDeEstudio/templates/includes/pagination.html
 <div class="cell">
    {% if is_paginated %}
        <nav aria-label="Pagination">
            <ul class="pagination">

                {% if page_obj.has_previous %}
                    <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}" style="color:white;">Anterior</li>
                {% endif %}

                {% for pagina in paginator.page_range %}

                    {% ifequal pagina page_obj.number %}
                        <li class="current">
                            <a style="color:white;" href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a>
                        </li>
                    {% else %}
                    <li><a style="color:white;" href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>
                    {% endifequal %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}" aria-label="Next page" style="color:white;">Siguiente</li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
 </div>