casoDeEstudio/applications/libro/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'libros_app'

urlpatterns = [
    path('libros/', views.ListLibros.as_view(), name='libros'),
    path('librosCategoria/<categoria>/', views.ListLibrosCategoria.as_view(), name='libros-categoria'),
    path('libroDetalle/<pk>/', views.LibroDetailView.as_view(), name='libro-detalle'),
    path('categorias/', views.CategoriaListView.as_view(), name='categorias'),
]

casoDeEstudio/applications/usuario/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'users_app'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name = 'user-register'),
    path('login/', views.UserLoginView.as_view(), name = 'user-login'),
    path('logout/', views.UserLogoutView.as_view(), name = 'user-logout'),
    path('user-verification/<pk>/', views.CodeVerificationView.as_view(), name = 'user-verification'),
    path('compra/<pk>/', views.OrdenView.as_view(), name = 'user-compra'),
    path('lista-ordenes/', views.OrdenesView.as_view(), name = 'user-ordenes'),
]

casoDeEstudio/casoDeEstudio/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.libro.urls')),
    re_path('', include('applications.usuario.urls')),
    re_path('', include('applications.home.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

casoDeEstudio/applications/libro/models.py
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from PIL import Image

from .managers import CategoriaManager, LibroManager


class Categoria(models.Model):
    nombre = models.CharField('Nombre', max_length=30)

    objects = CategoriaManager()

    def __str__(self):
        return str(self.id) + '-' + self.nombre
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

class Libro(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, verbose_name='Categoría', related_name='categoria_libro')
    autor = models.CharField(verbose_name='Autores',max_length=50)
    titulo = models.CharField('Titulo', max_length=50)
    fecha = models.DateField('Fecha de lanzamiento', auto_now=False, auto_now_add=False)
    portada = models.ImageField('Portada', upload_to='libro', blank=True, null=True)
    precio = models.PositiveIntegerField('Precio')
    inventario = models.PositiveIntegerField(default=10)

    objects = LibroManager()
    def __str__(self):
        return self.titulo

    class Meta:
        verbose_name = 'Libro'
        verbose_name_plural = 'Libros'
        ordering = ['titulo', 'fecha']

def optimize_image(sender, instance, **kargs):
    if(instance.portada):
        portada = Image.open(instance.portada.path)
        #con esto optimizamos y reducimos un 20% la calidad
        portada.save(instance.portada.path, quality = 20, optimize = True)
post_save.connect(optimize_image,sender= Libro)

casoDeEstudio/applications/libro/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
# Create your views here.
from .models import Libro, Categoria
# Create your views here.
class ListLibros(ListView):

    context_object_name = 'libros'
    paginate_by = 6
    template_name = 'libro/lista.html'

    def get_queryset(self):
        palabraClave = self.request.GET.get('nombre', '')
        return Libro.objects.buscarLibro(palabraClave)

class ListLibrosCategoria(ListView):

    context_object_name = 'libros'
    template_name = 'libro/lista_categoria.html'

    def get_queryset(self):
        categoria = self.kwargs['categoria']
        palabraClave = self.request.GET.get('nombre', '')
        return Libro.objects.listarLibrosCategoria(categoria, palabraClave)


class LibroDetailView(DetailView):
    model = Libro
    template_name = 'libro/detalle.html'

    def get_context_data(self, **kwargs):
        context = super(LibroDetailView, self).get_context_data(**kwargs)
        libroC = Libro.objects.get(pk=self.kwargs['pk'])
        context['recomendados'] = Libro.objects.listarLibrosRecomendados(libroC.categoria.id, libroC.id)
        return  context

class CategoriaListView(ListView):
    model = Categoria
    context_object_name = 'categorias'
    template_name = 'libro/categorias.html'
    paginate_by = 10

casoDeEstudio/templates/libro/categorias.html
{% extends 'base.html' %}

{% block titulo %} Lista categorias {% endblock titulo %}

{% block content %}
{% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista de Categorias</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for categoria in categorias %}
                        <tr>
                            <td>{{categoria.nombre}}</td>
                            <td><a class="button warning" href="{% url 'libros_app:libros-categoria' categoria.id %}">Ver Libros</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
             {% include 'includes/pagination.html' %}
        </div>
    </div>
{% endblock content %}

casoDeEstudio/templates/libro/detalle.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %} {{libro.titulo}} {% endblock titulo %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <h1 class="cell text-center">Detalles del libro</h1>
        <div class="card large-6 cell" style="width: 300px; margin-top: 10px;">
            <div class="card-divider">
            </div>

            {% if libro.portada %}
               <img src="{{libro.portada.url}}">
            {% else %}
               <img src="{% static 'img/libroDefault.png' %}">
            {% endif %}
            <div class="card-section">
              <h4>{{libro.titulo}}</h4>
              <p>Autor: {{libro.autor}}</p>
              <p>Fecha de lanzamiento: {{libro.fecha}}</p>
              <p>Genero: {{libro.categoria.nombre}}</p>
              <p>Cantidad disponible: {{libro.inventario}}</p>
              <p><span class="label">Precio:${{libro.precio}}</span></p>
                {% if libro.inventario >= 1 %}
              <a href="{% url 'users_app:user-compra' libro.id %}" class="btn btn-primary">Comprar</a>
                {% else %}
                <p class="btn btn-danger">No disponible</p>
                {% endif %}
            </div>
            <div class="card-divider">
                <p>Otros libros recomendados:</p>
                {% for recomendado in recomendados %}
                <p><a href='{% url "libros_app:libro-detalle" recomendado.id %}'>{{recomendado.titulo}}</a>
                {% endfor %}
            </div>
          </div>
    </div>
</div>
{% endblock content %}

casoDeEstudio/templates/libro/lista.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %} Todos los libros {% endblock titulo %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container grid-block" style="background-image: url('{% static "img/fondo-madera.jpg" %}'); width: 100%; height: 100vh;'">
    <div class="grid-x">
        <h1 style="color:white;">Libros</h1>
        <form class="cell grid-x grid-margin-x" method="GET"> {% csrf_token %}
            <div class="cell large-6 medium-8">
                <input type="text" id="nombre" name="nombre" placeholder="ingrese el titulo">
            </div>
            <div class="cell large-2 medium-3">
                 <button class = 'button success' type="submit">Buscar</button>
            </div>
        </form>
    </div>

        <div class="grid-x grid-margin-x small-up-2 medium-up-3 large-up-3">
            {% for libro in libros %}
          <div class="cell">
              {% if libro.portada %}
            <img class="thumbnail portada" src="{{libro.portada.url}}" style="width:40%">
              {% else %}
              <img class="thumbnail portada" src="{% static 'img/libroDefault.png' %}" >
              {% endif %}
            <h5 style="color:white;">{{libro.titulo}}</h5>
            <p style="color:white;">Genero: {{libro.categoria.nombre}}</p>
            <a href='{% url "libros_app:libro-detalle" libro.id %}' class="button small expanded">Ver</a>
          </div>
            {% endfor %}
        </div>
    {% include 'includes/pagination.html' %}
</div>
{% endblock content %}

casoDeEstudio/templates/libro/lista_categoria.html
{% extends 'base.html' %}
{% load static %}
{% block titulo %} Todos los libros de {{libros.first.categoria.nombre}}{% endblock titulo %}

{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container grid-block" style="background-image: url('{% static "img/fondo-madera.jpg" %}'); width: 100%; height: 100vh;'">
    <div class="grid-x">
        <h1 style="color:white;">Libros de {{libros.first.categoria.nombre}}</h1>
        <form class="cell grid-x grid-margin-x" method="GET"> {% csrf_token %}
            <div class="cell large-6 medium-8">
                <input type="text" id="nombre" name="nombre" placeholder="ingrese el titulo">
            </div>
            <div class="cell large-2 medium-3">
                 <button class = 'button success' type="submit">Buscar</button>
            </div>
        </form>
    </div>

        <div class="grid-x grid-margin-x small-up-2 medium-up-3 large-up-3">
            {% for libro in libros %}
          <div class="cell">
              {% if libro.portada %}
            <img class="thumbnail" src="{{libro.portada.url}}" style="width:40%;">
              {% else %}
              <img src="{% static 'img/libroDefault.png' %}" >
              {% endif %}
            <h5 style="color:white;">{{libro.titulo}}</h5>
            <a href="{% url 'libros_app:libro-detalle' libro.id %}" class="button small expanded">Ver</a>
          </div>
            {% endfor %}
        </div>
    {% include 'includes/pagination.html' %}
</div>
{% endblock content %}